services:
  - type: web
    name: mystudyplanner-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && chmod +x init.sh && ./init.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
